/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package perpustakaan;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author redmibook
 */
public class Buku1 extends javax.swing.JFrame {
    private DefaultTableModel model=null;
    private PreparedStatement stat;
    private ResultSet rs;
    koneksi k=new koneksi();

    /**
     * Creates new form 
     */
    public Buku1() {
        initComponents();
         this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        k.connect();
        refreshTable();
    }
    
    class tambahbarang extends Buku1{
        int id_buku,stok;
        String judul,pengarang,penerbit,kategori,deskripsi;
        
        public tambahbarang() {
            this.judul = textJudul.getText();
            this.pengarang = textPengarang.getText();
            this.penerbit = textPenerbit.getText();
             this.kategori = textKategori.getText();
              this.deskripsi = textDeskripsi.getText();
        }
    }
    
        
        public void refreshTable(){
            model= new DefaultTableModel();
            model.addColumn("ID Buku");
            model.addColumn("Judul Buku");
            model.addColumn("Pengarang");
            model.addColumn("Penerbit");
            model.addColumn("Kategori");
            model.addColumn("Deskripsi");
            model.addColumn("Stok");
            tabelbarang.setModel(model);
            try {
                this.stat=k.getKoneksi().prepareStatement("select * from buku");
                this.rs=this.stat.executeQuery();
                while(rs.next()){
                    Object[] data={
                        rs.getInt("id_buku"),
                        rs.getString("judul"),
                        rs.getString("pengarang"),
                        rs.getString("penerbit"),
                        rs.getString("kategori"),
                        rs.getString("deskripsi"),
                        rs.getInt("stok")
                    };
                    model.addRow(data);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null,e.getMessage());
            }
            textJudul.setText("");
            textPengarang.setText("");
            textPenerbit.setText("");   
            textKategori.setText("");     
            textDeskripsi.setText("");     
            textStok.setText("");    
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        textJudul = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        textPengarang = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        textPenerbit = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelbarang = new javax.swing.JTable();
        tombolsimpanbarang = new javax.swing.JButton();
        tombolgantibarang = new javax.swing.JButton();
        tombolhapusbarang = new javax.swing.JButton();
        btn_logout = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        idbuku = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        textKategori = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        textDeskripsi = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        textStok = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Rubik", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("JUDUL BUKU");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, 100, -1));

        textJudul.setBackground(new java.awt.Color(255, 255, 255,0));
        textJudul.setFont(new java.awt.Font("Rubik", 0, 18)); // NOI18N
        textJudul.setForeground(new java.awt.Color(255, 255, 255));
        textJudul.setText("JUDUL BUKU");
        textJudul.setBorder(null);
        textJudul.setOpaque(false);
        textJudul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textJudulActionPerformed(evt);
            }
        });
        getContentPane().add(textJudul, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, 690, 50));

        jLabel4.setFont(new java.awt.Font("Rubik", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("PENGARANG");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 450, 100, -1));

        textPengarang.setBackground(new java.awt.Color(255, 255, 255,0));
        textPengarang.setFont(new java.awt.Font("Rubik", 0, 18)); // NOI18N
        textPengarang.setForeground(new java.awt.Color(255, 255, 255));
        textPengarang.setText("PENGARANG");
        textPengarang.setBorder(null);
        textPengarang.setOpaque(false);
        getContentPane().add(textPengarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 470, 700, 50));

        jLabel1.setFont(new java.awt.Font("Rubik", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PENERBIT");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 540, 100, -1));

        textPenerbit.setBackground(new java.awt.Color(255, 255, 255,0));
        textPenerbit.setFont(new java.awt.Font("Rubik", 0, 18)); // NOI18N
        textPenerbit.setForeground(new java.awt.Color(255, 255, 255));
        textPenerbit.setText("PENERBIT");
        textPenerbit.setBorder(null);
        textPenerbit.setOpaque(false);
        getContentPane().add(textPenerbit, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 560, 690, 60));

        tabelbarang.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(142, 114, 69), 1, true));
        tabelbarang.setFont(new java.awt.Font("Rubik", 0, 13)); // NOI18N
        tabelbarang.setForeground(new java.awt.Color(0, 0, 102));
        tabelbarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelbarang.setFocusable(false);
        tabelbarang.setGridColor(new java.awt.Color(0, 0, 102));
        tabelbarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelbarangMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelbarang);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 285, 900, 710));

        tombolsimpanbarang.setBackground(new java.awt.Color(255, 255, 255,0));
        tombolsimpanbarang.setFont(new java.awt.Font("Rubik", 0, 18)); // NOI18N
        tombolsimpanbarang.setForeground(new java.awt.Color(255, 255, 255));
        tombolsimpanbarang.setText("Simpan");
        tombolsimpanbarang.setBorderPainted(false);
        tombolsimpanbarang.setFocusPainted(false);
        tombolsimpanbarang.setFocusable(false);
        tombolsimpanbarang.setOpaque(false);
        tombolsimpanbarang.setRequestFocusEnabled(false);
        tombolsimpanbarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolsimpanbarangActionPerformed(evt);
            }
        });
        getContentPane().add(tombolsimpanbarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 940, 140, 50));

        tombolgantibarang.setBackground(new java.awt.Color(255, 255, 255,0));
        tombolgantibarang.setFont(new java.awt.Font("Rubik", 0, 18)); // NOI18N
        tombolgantibarang.setForeground(new java.awt.Color(255, 255, 255));
        tombolgantibarang.setText("Ganti");
        tombolgantibarang.setBorderPainted(false);
        tombolgantibarang.setFocusPainted(false);
        tombolgantibarang.setFocusable(false);
        tombolgantibarang.setOpaque(false);
        tombolgantibarang.setRequestFocusEnabled(false);
        tombolgantibarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolgantibarangActionPerformed(evt);
            }
        });
        getContentPane().add(tombolgantibarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 940, 150, 50));

        tombolhapusbarang.setBackground(new java.awt.Color(255, 255, 255,0));
        tombolhapusbarang.setFont(new java.awt.Font("Rubik", 0, 18)); // NOI18N
        tombolhapusbarang.setForeground(new java.awt.Color(255, 255, 255));
        tombolhapusbarang.setText("Hapus");
        tombolhapusbarang.setBorderPainted(false);
        tombolhapusbarang.setFocusPainted(false);
        tombolhapusbarang.setFocusable(false);
        tombolhapusbarang.setOpaque(false);
        tombolhapusbarang.setRequestFocusEnabled(false);
        tombolhapusbarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolhapusbarangActionPerformed(evt);
            }
        });
        getContentPane().add(tombolhapusbarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 940, 140, 50));

        btn_logout.setBackground(new java.awt.Color(255, 255, 255,0));
        btn_logout.setFont(new java.awt.Font("Rubik", 0, 18)); // NOI18N
        btn_logout.setForeground(new java.awt.Color(255, 255, 255));
        btn_logout.setText("Kembali");
        btn_logout.setBorderPainted(false);
        btn_logout.setFocusPainted(false);
        btn_logout.setFocusable(false);
        btn_logout.setOpaque(false);
        btn_logout.setRequestFocusEnabled(false);
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });
        getContentPane().add(btn_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1600, 130, 140, 50));

        jLabel2.setFont(new java.awt.Font("Rubik", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID BUKU");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 100, -1));

        idbuku.setBackground(new java.awt.Color(255, 255, 255,0));
        idbuku.setFont(new java.awt.Font("Rubik", 0, 18)); // NOI18N
        idbuku.setForeground(new java.awt.Color(102, 204, 255));
        idbuku.setText("ID BUKU");
        idbuku.setBorder(null);
        idbuku.setEnabled(false);
        idbuku.setFocusable(false);
        idbuku.setOpaque(false);
        idbuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idbukuActionPerformed(evt);
            }
        });
        getContentPane().add(idbuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 690, 60));

        jLabel6.setFont(new java.awt.Font("Rubik", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("KATEGORI");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 630, 100, -1));

        textKategori.setBackground(new java.awt.Color(255, 255, 255,0));
        textKategori.setFont(new java.awt.Font("Rubik", 0, 18)); // NOI18N
        textKategori.setForeground(new java.awt.Color(255, 255, 255));
        textKategori.setText("KATEGORI");
        textKategori.setBorder(null);
        textKategori.setOpaque(false);
        getContentPane().add(textKategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 660, 700, 50));

        jLabel7.setFont(new java.awt.Font("Rubik", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("DESKRIPSI");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 730, 100, -1));

        textDeskripsi.setBackground(new java.awt.Color(255, 255, 255,0));
        textDeskripsi.setFont(new java.awt.Font("Rubik", 0, 18)); // NOI18N
        textDeskripsi.setForeground(new java.awt.Color(255, 255, 255));
        textDeskripsi.setText("DESKRIPSI");
        textDeskripsi.setBorder(null);
        textDeskripsi.setOpaque(false);
        getContentPane().add(textDeskripsi, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 750, 680, 50));

        jLabel5.setFont(new java.awt.Font("Rubik", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("STOK");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 820, 100, -1));

        textStok.setBackground(new java.awt.Color(255, 255, 255,0));
        textStok.setFont(new java.awt.Font("Rubik", 0, 18)); // NOI18N
        textStok.setForeground(new java.awt.Color(255, 255, 255));
        textStok.setText("STOK");
        textStok.setBorder(null);
        textStok.setOpaque(false);
        getContentPane().add(textStok, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 840, 680, 60));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/perpustakaan/4.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tombolhapusbarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolhapusbarangActionPerformed
        // TODO add your handling code here:
        try {
            this.stat=k.getKoneksi().prepareStatement("delete from buku where id_buku=?");       
            stat.setInt(1, Integer.parseInt(idbuku.getText()));
            stat.executeUpdate();
            refreshTable();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }//GEN-LAST:event_tombolhapusbarangActionPerformed

    private void textJudulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textJudulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textJudulActionPerformed

    private void tombolgantibarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolgantibarangActionPerformed
        // TODO add your handling code here:
        try {
            tambahbarang b=new tambahbarang();
            this.stat=k.getKoneksi().prepareStatement("update buku set judul=?,"
                    + "pengarang=?,penerbit=?,kategori=?,deskripsi=?,stok=? where id_buku=?");
            
            stat.setString(1, b.judul);
            stat.setString(2, b.pengarang);
            stat.setString(3,b.penerbit);
            stat.setString(4,b.kategori);
            stat.setString(5,b.deskripsi);
            stat.setInt(6, Integer.parseInt(textStok.getText()));
            stat.setInt(7, Integer.parseInt(idbuku.getText()));
            stat.executeUpdate();
            refreshTable();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }//GEN-LAST:event_tombolgantibarangActionPerformed

    private void tombolsimpanbarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolsimpanbarangActionPerformed
        // TODO add your handling code here:
        try {
            tambahbarang b=new tambahbarang();
            this.stat=k.getKoneksi().prepareStatement("insert into buku values (?,?,?,?,?,?,?)");
            stat.setInt(1, b.id_buku);
            stat.setString(2, b.judul);
            stat.setString(3, b.pengarang);
            stat.setString(4,b.penerbit);
            stat.setString(5,b.kategori);
            stat.setString(6,b.deskripsi);
             stat.setInt(7, Integer.parseInt(textStok.getText()));
            stat.executeUpdate();
            refreshTable();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }//GEN-LAST:event_tombolsimpanbarangActionPerformed

    private void tabelbarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelbarangMouseClicked
        // TODO add your handling code here:
        idbuku.setText(model.getValueAt(tabelbarang.getSelectedRow(), 0).toString());
        textJudul.setText(model.getValueAt(tabelbarang.getSelectedRow(), 1).toString());
        textPengarang.setText(model.getValueAt(tabelbarang.getSelectedRow(), 2).toString());
        textPenerbit.setText(model.getValueAt(tabelbarang.getSelectedRow(), 3).toString());
        textKategori.setText(model.getValueAt(tabelbarang.getSelectedRow(), 4).toString());
        textDeskripsi.setText(model.getValueAt(tabelbarang.getSelectedRow(), 5).toString());
        textStok.setText(model.getValueAt(tabelbarang.getSelectedRow(), 6).toString());
    }//GEN-LAST:event_tabelbarangMouseClicked

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        // TODO add your handling code here:
        new DashKepala().show();
this.dispose();

    }//GEN-LAST:event_btn_logoutActionPerformed

    private void idbukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idbukuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idbukuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Buku1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Buku1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Buku1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Buku1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Buku1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_logout;
    private javax.swing.JTextField idbuku;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tabelbarang;
    private javax.swing.JTextField textDeskripsi;
    private javax.swing.JTextField textJudul;
    private javax.swing.JTextField textKategori;
    private javax.swing.JTextField textPenerbit;
    private javax.swing.JTextField textPengarang;
    private javax.swing.JTextField textStok;
    private javax.swing.JButton tombolgantibarang;
    private javax.swing.JButton tombolhapusbarang;
    private javax.swing.JButton tombolsimpanbarang;
    // End of variables declaration//GEN-END:variables
}
