/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package perpustakaan;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author redmibook
 */
public class Siswa1 extends javax.swing.JFrame {
    private DefaultTableModel model=null;
    private PreparedStatement stat;
    private ResultSet rs;
    koneksi k=new koneksi();

    /**
     * Creates new form 
     */
    public Siswa1() {
        initComponents();
         this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        k.connect();
        refreshTable();
    }
    
    class tambahbarang extends Siswa1{
        int id_siswa;
        String nama,nis,kelas,jenis_kelamin;
        
        public tambahbarang() {
            this.nama = texNama.getText();
            this.nis = textNis.getText();
            this.kelas = textKelas.getText();
             this.jenis_kelamin =  (String)cbKelamin.getSelectedItem();
        }
    }
    
        
        public void refreshTable(){
            model= new DefaultTableModel();
            model.addColumn("ID Siswa");
            model.addColumn("Nama Siswa");
            model.addColumn("NIS");
            model.addColumn("Kelas");
            model.addColumn("Jenis Kelamin");
            tabelbarang.setModel(model);
            try {
                this.stat=k.getKoneksi().prepareStatement("select * from siswa");
                this.rs=this.stat.executeQuery();
                while(rs.next()){
                    Object[] data={
                        rs.getInt("id_siswa"),
                        rs.getString("nama"),
                        rs.getString("nis"),
                        rs.getString("kelas"),
                        rs.getString("jenis_kelamin"),
                    };
                    model.addRow(data);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null,e.getMessage());
            }
            texNama.setText("");
            textNis.setText("");
            textKelas.setText("");   
            cbKelamin.setSelectedItem("");     
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        texNama = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        textNis = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        textKelas = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelbarang = new javax.swing.JTable();
        tombolsimpanbarang = new javax.swing.JButton();
        tombolgantibarang = new javax.swing.JButton();
        tombolhapusbarang = new javax.swing.JButton();
        btn_logout = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        idsiswa = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cbKelamin = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Rubik", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("NAMA SISWA");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, 100, -1));

        texNama.setBackground(new java.awt.Color(255, 255, 255,0));
        texNama.setFont(new java.awt.Font("Rubik", 0, 18)); // NOI18N
        texNama.setForeground(new java.awt.Color(255, 255, 255));
        texNama.setText("NAMA SISWA");
        texNama.setBorder(null);
        texNama.setOpaque(false);
        texNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texNamaActionPerformed(evt);
            }
        });
        getContentPane().add(texNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, 680, 70));

        jLabel4.setFont(new java.awt.Font("Rubik", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("NIS");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 470, 100, -1));

        textNis.setBackground(new java.awt.Color(255, 255, 255,0));
        textNis.setFont(new java.awt.Font("Rubik", 0, 18)); // NOI18N
        textNis.setForeground(new java.awt.Color(255, 255, 255));
        textNis.setText("NOMOR INDUK SISWA");
        textNis.setBorder(null);
        textNis.setOpaque(false);
        textNis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNisActionPerformed(evt);
            }
        });
        getContentPane().add(textNis, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 490, 680, 70));

        jLabel1.setFont(new java.awt.Font("Rubik", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("KELAS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 580, 100, -1));

        textKelas.setBackground(new java.awt.Color(255, 255, 255,0));
        textKelas.setFont(new java.awt.Font("Rubik", 0, 18)); // NOI18N
        textKelas.setForeground(new java.awt.Color(255, 255, 255));
        textKelas.setText("KELAS");
        textKelas.setBorder(null);
        textKelas.setOpaque(false);
        getContentPane().add(textKelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 600, 680, 60));

        tabelbarang.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(142, 114, 69), 1, true));
        tabelbarang.setFont(new java.awt.Font("Rubik", 0, 13)); // NOI18N
        tabelbarang.setForeground(new java.awt.Color(0, 0, 102));
        tabelbarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelbarang.setFocusable(false);
        tabelbarang.setGridColor(new java.awt.Color(0, 0, 102));
        tabelbarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelbarangMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelbarang);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 285, 900, 600));

        tombolsimpanbarang.setBackground(new java.awt.Color(255, 255, 255,0));
        tombolsimpanbarang.setFont(new java.awt.Font("Rubik", 0, 18)); // NOI18N
        tombolsimpanbarang.setForeground(new java.awt.Color(255, 255, 255));
        tombolsimpanbarang.setText("Simpan");
        tombolsimpanbarang.setBorderPainted(false);
        tombolsimpanbarang.setFocusPainted(false);
        tombolsimpanbarang.setFocusable(false);
        tombolsimpanbarang.setOpaque(false);
        tombolsimpanbarang.setRequestFocusEnabled(false);
        tombolsimpanbarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolsimpanbarangActionPerformed(evt);
            }
        });
        getContentPane().add(tombolsimpanbarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 830, 140, 50));

        tombolgantibarang.setBackground(new java.awt.Color(255, 255, 255,0));
        tombolgantibarang.setFont(new java.awt.Font("Rubik", 0, 18)); // NOI18N
        tombolgantibarang.setForeground(new java.awt.Color(255, 255, 255));
        tombolgantibarang.setText("Ganti");
        tombolgantibarang.setBorderPainted(false);
        tombolgantibarang.setFocusPainted(false);
        tombolgantibarang.setFocusable(false);
        tombolgantibarang.setOpaque(false);
        tombolgantibarang.setRequestFocusEnabled(false);
        tombolgantibarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolgantibarangActionPerformed(evt);
            }
        });
        getContentPane().add(tombolgantibarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 830, 150, 50));

        tombolhapusbarang.setBackground(new java.awt.Color(255, 255, 255,0));
        tombolhapusbarang.setFont(new java.awt.Font("Rubik", 0, 18)); // NOI18N
        tombolhapusbarang.setForeground(new java.awt.Color(255, 255, 255));
        tombolhapusbarang.setText("Hapus");
        tombolhapusbarang.setBorderPainted(false);
        tombolhapusbarang.setFocusPainted(false);
        tombolhapusbarang.setFocusable(false);
        tombolhapusbarang.setOpaque(false);
        tombolhapusbarang.setRequestFocusEnabled(false);
        tombolhapusbarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolhapusbarangActionPerformed(evt);
            }
        });
        getContentPane().add(tombolhapusbarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 830, 140, 50));

        btn_logout.setBackground(new java.awt.Color(255, 255, 255,0));
        btn_logout.setFont(new java.awt.Font("Rubik", 0, 18)); // NOI18N
        btn_logout.setForeground(new java.awt.Color(255, 255, 255));
        btn_logout.setText("Kembali");
        btn_logout.setBorderPainted(false);
        btn_logout.setFocusPainted(false);
        btn_logout.setFocusable(false);
        btn_logout.setOpaque(false);
        btn_logout.setRequestFocusEnabled(false);
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });
        getContentPane().add(btn_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1600, 130, 140, 50));

        jLabel2.setFont(new java.awt.Font("Rubik", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID SISWA");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 100, -1));

        idsiswa.setBackground(new java.awt.Color(255, 255, 255,0));
        idsiswa.setFont(new java.awt.Font("Rubik", 0, 18)); // NOI18N
        idsiswa.setForeground(new java.awt.Color(102, 204, 255));
        idsiswa.setText("ID SISWA");
        idsiswa.setBorder(null);
        idsiswa.setEnabled(false);
        idsiswa.setFocusable(false);
        idsiswa.setOpaque(false);
        idsiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idsiswaActionPerformed(evt);
            }
        });
        getContentPane().add(idsiswa, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 680, 70));

        jLabel6.setFont(new java.awt.Font("Rubik", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("JENIS KELAMIN");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 680, 130, -1));

        cbKelamin.setFont(new java.awt.Font("Rubik", 0, 18)); // NOI18N
        cbKelamin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Perempuan", "Laki-laki" }));
        cbKelamin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        cbKelamin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cbKelamin.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        cbKelamin.setOpaque(false);
        getContentPane().add(cbKelamin, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 700, 690, 70));

        jLabel9.setBackground(new java.awt.Color(0, 0, 51));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/perpustakaan/6.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tombolhapusbarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolhapusbarangActionPerformed
        // TODO add your handling code here:
        try {
            this.stat=k.getKoneksi().prepareStatement("delete from siswa where id_siswa=?");       
            stat.setInt(1, Integer.parseInt(idsiswa.getText()));
            stat.executeUpdate();
            refreshTable();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }//GEN-LAST:event_tombolhapusbarangActionPerformed

    private void texNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texNamaActionPerformed

    private void tombolgantibarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolgantibarangActionPerformed
        // TODO add your handling code here:
        try {
            tambahbarang b=new tambahbarang();
            this.stat=k.getKoneksi().prepareStatement("update siswa set nama=?,"
                    + "nis=?,kelas=?,jenis_kelamin=? where id_siswa=?");
            
            stat.setString(1, b.nama);
            stat.setString(2, b.nis);
            stat.setString(3,b.kelas);
            stat.setString(4,b.jenis_kelamin);
            stat.setInt(5, Integer.parseInt(idsiswa.getText()));
            stat.executeUpdate();
            refreshTable();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }//GEN-LAST:event_tombolgantibarangActionPerformed

    private void tombolsimpanbarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolsimpanbarangActionPerformed
        // TODO add your handling code here:
        try {
            tambahbarang b=new tambahbarang();
            this.stat=k.getKoneksi().prepareStatement("insert into siswa values (?,?,?,?,?)");
            stat.setInt(1, b.id_siswa);
            stat.setString(2, b.nama);
            stat.setString(3, b.nis);
            stat.setString(4,b.kelas);
            stat.setString(5,b.jenis_kelamin);
            stat.executeUpdate();
            refreshTable();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }//GEN-LAST:event_tombolsimpanbarangActionPerformed

    private void tabelbarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelbarangMouseClicked
        // TODO add your handling code here:
        idsiswa.setText(model.getValueAt(tabelbarang.getSelectedRow(), 0).toString());
        texNama.setText(model.getValueAt(tabelbarang.getSelectedRow(), 1).toString());
        textNis.setText(model.getValueAt(tabelbarang.getSelectedRow(), 2).toString());
        textKelas.setText(model.getValueAt(tabelbarang.getSelectedRow(), 3).toString());
        cbKelamin.setSelectedItem(model.getValueAt(tabelbarang.getSelectedRow(), 4).toString());
    }//GEN-LAST:event_tabelbarangMouseClicked

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        // TODO add your handling code here:
        new DashKepala().show();
this.dispose();

    }//GEN-LAST:event_btn_logoutActionPerformed

    private void idsiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idsiswaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idsiswaActionPerformed

    private void textNisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Siswa1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Siswa1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Siswa1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Siswa1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Siswa1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_logout;
    private javax.swing.JComboBox<String> cbKelamin;
    private javax.swing.JTextField idsiswa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tabelbarang;
    private javax.swing.JTextField texNama;
    private javax.swing.JTextField textKelas;
    private javax.swing.JTextField textNis;
    private javax.swing.JButton tombolgantibarang;
    private javax.swing.JButton tombolhapusbarang;
    private javax.swing.JButton tombolsimpanbarang;
    // End of variables declaration//GEN-END:variables
}
